version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - MONGODB_URL=mongodb://db:27017/news-app
    networks:
      - app_net
  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app_net
networks:
  app_net:
volumes:
  mongo_data: